#!/usr/bin/env bash
#
# TruckAI — one command from a clean server to a running production deployment.
#
#   sudo bash deploy/go-live.sh --domain truckai.uz --email admin@truckai.uz
#
# What it does, in the order that matters:
#
#   1. refuses to continue if the prerequisites are missing
#   2. generates .env.production with real secrets (or reuses an existing one)
#   3. BACKS UP the database if one already exists — before any migration
#   4. builds the web bundle against this deployment's own origin
#   5. brings the stack up: migrations run once, then the API starts
#   6. issues the TLS certificate
#   7. creates the first administrator
#   8. runs the smoke test and refuses to declare success if anything fails
#
# It is safe to re-run. On a second run it reuses the existing environment
# file and secrets, takes a fresh backup, applies only pending migrations, and
# never touches existing data.
#
# --dry-run prints every step without changing anything.
set -euo pipefail

DOMAIN=""
EMAIL=""
MODE="single-server"   # or: api-only  (frontend on Vercel)
DRY_RUN=false
ENV_FILE="${ENV_FILE:-.env.production}"
COMPOSE="docker compose -f docker-compose.prod.yml --env-file $ENV_FILE"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)   DOMAIN="$2"; shift 2 ;;
    --email)    EMAIL="$2"; shift 2 ;;
    --mode)     MODE="$2"; shift 2 ;;
    --dry-run)  DRY_RUN=true; shift ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

step() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
die()  { printf '  \033[31m✗\033[0m %s\n' "$*" >&2; exit 1; }
run()  { if $DRY_RUN; then printf '  [dry-run] %s\n' "$*"; else eval "$@"; fi; }

# ---------------------------------------------------------------------------
step "1/8  Prerequisites"
# ---------------------------------------------------------------------------
[[ -n "$DOMAIN" ]] || die "--domain is required (e.g. --domain truckai.uz)"
[[ -n "$EMAIL"  ]] || die "--email is required — Let's Encrypt sends expiry warnings there"
[[ "$MODE" == "single-server" || "$MODE" == "api-only" ]] || die "--mode must be single-server or api-only"

for tool in docker openssl curl; do
  command -v "$tool" >/dev/null 2>&1 || die "$tool is not installed"
done
docker compose version >/dev/null 2>&1 || die "docker compose v2 is not available"
ok "tooling present"

# DNS has to be right before certbot is asked to prove anything, and a wrong
# answer here costs a Let's Encrypt rate-limit slot rather than a retry.
RESOLVED="$(getent hosts "$DOMAIN" | awk '{print $1}' | head -n1 || true)"
if [[ -z "$RESOLVED" ]]; then
  die "$DOMAIN does not resolve. Point an A record at this server and wait for the TTL."
fi
ok "$DOMAIN resolves to $RESOLVED"

# ---------------------------------------------------------------------------
step "2/8  Environment"
# ---------------------------------------------------------------------------
if [[ -f "$ENV_FILE" ]]; then
  ok "reusing the existing $ENV_FILE (secrets are NOT regenerated)"
else
  if $DRY_RUN; then
    printf '  [dry-run] would generate %s with fresh secrets\n' "$ENV_FILE"
  else
    DB_PASSWORD="$(openssl rand -hex 24)"
    if [[ "$MODE" == "single-server" ]]; then
      APP_ORIGIN="https://$DOMAIN"
      NGINX_CONF="./deploy/nginx.single-server.conf"
    else
      APP_ORIGIN="https://app.$DOMAIN"
      NGINX_CONF="./deploy/nginx.conf"
    fi

    cat > "$ENV_FILE" <<EOF
# Generated by deploy/go-live.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Never commit this file. Keep a copy of BACKUP_PASSPHRASE somewhere else.
NODE_ENV=production
API_PORT=3000

POSTGRES_USER=truckai
POSTGRES_PASSWORD=$DB_PASSWORD
POSTGRES_DB=truckai
DATABASE_URL=postgresql://truckai:$DB_PASSWORD@postgres:5432/truckai?schema=public

WEB_URL=$APP_ORIGIN
TRUST_PROXY=1

JWT_ACCESS_SECRET=$(openssl rand -base64 48 | tr -d '\n')
JWT_REFRESH_SECRET=$(openssl rand -base64 48 | tr -d '\n')
JWT_ACCESS_TTL=15m
JWT_REFRESH_TTL=30d

MINIO_ROOT_USER=truckai
MINIO_ROOT_PASSWORD=$(openssl rand -hex 20)
MINIO_BUCKET=truckai

AI_PROVIDER=mock
AI_API_KEY=
AI_ENABLED=true

BACKUP_PASSPHRASE=$(openssl rand -base64 24 | tr -d '\n')
BACKUP_RETENTION_DAYS=30
BACKUP_S3_TARGET=

NGINX_CONF=$NGINX_CONF
WEB_DIST=./apps/web/dist
API_REPLICAS=2
EOF
    chmod 600 "$ENV_FILE"
    ok "generated $ENV_FILE with fresh secrets (chmod 600)"
  fi
fi

if ! $DRY_RUN; then
  sh deploy/check-production-env.sh "$ENV_FILE" || die "the environment file is not deployable"
fi

# ---------------------------------------------------------------------------
step "3/8  Backup before touching the schema"
# ---------------------------------------------------------------------------
# On a first deployment there is nothing to back up. On every later run there
# is, and taking it BEFORE the migration is the only thing that makes a bad
# migration recoverable.
if $DRY_RUN; then
  printf '  [dry-run] would back up the database if one exists\n'
elif $COMPOSE ps --status running --services 2>/dev/null | grep -qx postgres; then
  # shellcheck disable=SC1090
  set -a; . "$ENV_FILE"; set +a
  $COMPOSE exec -T postgres sh -c \
    "PGPASSWORD='$POSTGRES_PASSWORD' pg_dump -U '$POSTGRES_USER' -d '$POSTGRES_DB' --format=custom" \
    > "/tmp/truckai_pre_deploy_$(date -u +%Y%m%d_%H%M%SZ).dump" \
    || die "the pre-deploy backup failed — NOT continuing"
  ok "pre-deploy backup written to /tmp"
else
  ok "first deployment — no existing database to back up"
fi

# ---------------------------------------------------------------------------
step "4/8  Web bundle"
# ---------------------------------------------------------------------------
if [[ "$MODE" == "single-server" ]]; then
  # Same origin: the bundle asks whichever host served it, so it cannot be
  # built pointing at the wrong API.
  API_URL="/api/v1"
else
  API_URL="https://api.$DOMAIN/api/v1"
fi
run "VITE_API_URL='$API_URL' pnpm install --frozen-lockfile"
run "VITE_API_URL='$API_URL' pnpm --filter shared build"
run "VITE_API_URL='$API_URL' pnpm --filter web build"
ok "web bundle built against $API_URL"

# ---------------------------------------------------------------------------
step "5/8  Bring the stack up"
# ---------------------------------------------------------------------------
# `migrate` is a one-shot service that must succeed before `api` starts, so a
# failed migration stops the deployment instead of half-applying it.
run "$COMPOSE build"
run "$COMPOSE up -d"

# The roles file has to run again once the schema exists: `_prisma_migrations`
# is created by the migration itself, so the REVOKE that keeps the application
# role out of the migration bookkeeping cannot run on the first pass. Idempotent.
if ! $DRY_RUN && [[ -f deploy/postgres-roles.sql ]]; then
  $COMPOSE exec -T postgres psql -U "${POSTGRES_USER:-truckai}" -d "${POSTGRES_DB:-truckai}" \
    -v app_password="'placeholder-not-used-on-second-pass'" \
    -v migrator_password="'placeholder-not-used-on-second-pass'" \
    -f /dev/stdin < deploy/postgres-roles.sql >/dev/null 2>&1 \
    && ok "database roles re-applied after migration" \
    || printf '  note: run deploy/postgres-roles.sql again by hand to finish role hardening\n'
fi

if ! $DRY_RUN; then
  printf '  waiting for the API to become ready'
  for _ in $(seq 1 60); do
    if $COMPOSE exec -T api curl -fsS http://127.0.0.1:3000/api/v1/health/ready >/dev/null 2>&1; then
      printf '\n'; ok "API is ready"; break
    fi
    printf '.'; sleep 2
  done
  $COMPOSE exec -T api curl -fsS http://127.0.0.1:3000/api/v1/health/ready >/dev/null 2>&1 \
    || { printf '\n'; $COMPOSE logs --tail 50 api migrate; die "the API never became ready"; }
fi

# ---------------------------------------------------------------------------
step "6/8  TLS certificate"
# ---------------------------------------------------------------------------
if $DRY_RUN; then
  printf '  [dry-run] would issue a certificate for %s\n' "$DOMAIN"
elif [[ -f deploy/certs/fullchain.pem ]]; then
  ok "a certificate is already installed — renewal is handled by the timer"
else
  sh deploy/certbot.sh issue "$DOMAIN" "$EMAIL" || die "certificate issuance failed"
  [[ "$MODE" == "api-only" ]] && sh deploy/certbot.sh issue "api.$DOMAIN" "$EMAIL"
  sh deploy/certbot.sh install-timer || true
  ok "certificate issued and automatic renewal installed"
fi

# ---------------------------------------------------------------------------
step "7/8  First administrator"
# ---------------------------------------------------------------------------
if $DRY_RUN; then
  printf '  [dry-run] would create the first administrator\n'
elif [[ -f .superadmin-created ]]; then
  ok "the administrator already exists — skipping"
else
  ADMIN_PASSWORD="$(openssl rand -base64 18)"
  $COMPOSE run --rm \
    -e SUPERADMIN_EMAIL="admin@$DOMAIN" \
    -e SUPERADMIN_PASSWORD="$ADMIN_PASSWORD" \
    -e SUPERADMIN_NAME="Platform Administrator" \
    api npx prisma db seed >/dev/null || die "seeding the administrator failed"
  touch .superadmin-created
  ok "administrator created"
  printf '\n  \033[1mWRITE THESE DOWN NOW — the password is never shown again:\033[0m\n'
  printf '    login: admin@%s\n    password: %s\n\n' "$DOMAIN" "$ADMIN_PASSWORD"
fi

# ---------------------------------------------------------------------------
step "8/8  Smoke test against the real deployment"
# ---------------------------------------------------------------------------
if $DRY_RUN; then
  printf '  [dry-run] would run deploy/smoke-test.sh against https://%s\n' "$DOMAIN"
  exit 0
fi

if [[ "$MODE" == "single-server" ]]; then
  SMOKE_BASE="https://$DOMAIN"; SMOKE_WEB="https://$DOMAIN"
else
  SMOKE_BASE="https://api.$DOMAIN"; SMOKE_WEB="https://app.$DOMAIN"
fi

if BASE_URL="$SMOKE_BASE" WEB_BASE_URL="$SMOKE_WEB" bash deploy/smoke-test.sh; then
  printf '\n\033[1;32mDEPLOYMENT COMPLETE\033[0m — %s\n' "$SMOKE_WEB"
  printf 'Next: create the client company from the admin account, then hand over the login.\n'
else
  die "the smoke test failed — the deployment is up but NOT ready to hand over"
fi
